### ISSUE TITLE
What are the requirements for the script to work?

### ISSUE THREAD

**Issue by Bazze** [pixelriot/SVG2Godot#2]
Hey!

I found your script and got my hopes up! 😄 However, I've tried a bunch of SVG files and haven't managed to get any to work reliably. What would you say the requirements are for this script to work well as-is?

For example, [this SVG](https://cdn.clipart.email/ede04fbe055e7de1fdfb5caf1e9b4030_lady-and-the-tramp-in-love-coloring-page-disney-lol_612-792.svg) ended up like this: 

<img width="935" alt="Screenshot 2020-04-16 at 20 22 30" src="https://user-images.githubusercontent.com/1932208/79492259-03d7bb00-8020-11ea-85d5-8011e2bf0ca9.png">

Thanks and nice work!

**Comment by pixelriot** [comment]
Unfortunately, since Godot does not have a proper "path"-node, the script is not intended to import complex paths. 
However, I opened and re-saved the svg-file in Inkscape and got the following result (after rearranging some of the resulting shapes):

![grafik](https://user-images.githubusercontent.com/21098503/79546433-ba748380-8092-11ea-9af7-8882158d4f1d.png)

You can also try out setting var use_path2d = true to get propper paths via Path2D node. However, those are only visible in the editor:

![grafik](https://user-images.githubusercontent.com/21098503/79546589-f871a780-8092-11ea-9a6f-927228afe31b.png)

**Comment by Bazze** [comment]
Ah, nice! Thanks for the pointers 😊
